### ISSUE TITLE
Utilize a estrutura base de uma página HTML (Isso não é um problema real)

### ISSUE THREAD

**Issue by AirckLima** [Hadryanns/i.p.web#2]
Antes de tudo, muito bacana o estudo.

Dito isso, uma boa prática para construir páginas html é iniciar com a estrutura padrão:
1. DOCTYPE
2. tag HTML
3. head (informações para o seu navegador)
4. body (aqui vai seu conteúdo)

 (VERIFICAR: https://developer.mozilla.org/pt-BR/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure)

---
### DICA
Caso esteja usando o VScode, há uma maneira rápida de usar um modelo base com apenas uma tecla:

1. Digite o caractere ___"!"___ :
![image](https://github.com/Hadryanns/i.p.web/assets/93441113/85a1a762-c856-4129-852a-c5d0b3a8cf66)

2. Aperte ___Enter___ para ele adicionar o modelo:
![image](https://github.com/Hadryanns/i.p.web/assets/93441113/5c33d2b7-0fd3-415c-b801-47aa0d978222)

3. Altere como quiser:
![image](https://github.com/Hadryanns/i.p.web/assets/93441113/1cb0b348-a6de-485b-bbd0-9cf38052b161)

Bons estudos!

**Comment by Hadryanns** [comment]
Noooossa, valeu, to aprendendo agora mexer no web e talz, to pesquisando aos poucos, usando git bash tb, facilita mt, depois vou dar uma olhada no conteúdo, esse final de semana quero fazer tipo um ficheiro nessa página web teste, que o professor pediu, fazer um négocio mais organizado.
